name: Writeme

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
      
    - name: Generate Readme
      run: |-
        bundle exec ruby writeme.rb
        cat README.md
        
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "potbye@users.noreply.github.com"
        git config --global user.name "potbye"
        git add -A
        git commit -m "Update Readme.md" || exit 0
        git push


